insert into Alumno (Usuario_idUsuario, Escuela) values (1001, 'University of Bath');
insert into Alumno (Usuario_idUsuario, Escuela) values (1007, 'Indiana University - Southeast');
insert into Alumno (Usuario_idUsuario, Escuela) values (10011, 'Valdosta State University');
insert into Alumno (Usuario_idUsuario, Escuela) values (10014, 'Atish Dipankar University');
insert into Alumno (Usuario_idUsuario, Escuela) values (10015, 'Indian Institute of Technology, Hyderabad');
insert into Alumno (Usuario_idUsuario, Escuela) values (10017, 'Université de M''sila');
insert into Alumno (Usuario_idUsuario, Escuela) values (10020, 'Voronezh State Technical University');
insert into Alumno (Usuario_idUsuario, Escuela) values (10023, 'University of Cyprus');
insert into Alumno (Usuario_idUsuario, Escuela) values (10025, 'Suez Canal University');
insert into Alumno (Usuario_idUsuario, Escuela) values (10026, 'University of Nottingham');
insert into Alumno (Usuario_idUsuario, Escuela) values (10029, 'National University of Theater and Film Arts');
insert into Alumno (Usuario_idUsuario, Escuela) values (10030, 'Anhui Technical College of Water Resources and Hydroelectric Power');
insert into Alumno (Usuario_idUsuario, Escuela) values (10031, 'Ecole Nationale Supérieure des Mines d''Alès');
insert into Alumno (Usuario_idUsuario, Escuela) values (10033, 'Ecole Nationale Supérieur de Géologie de Nancy');
insert into Alumno (Usuario_idUsuario, Escuela) values (10038, 'Ferghana Politechnical Institute');
insert into Alumno (Usuario_idUsuario, Escuela) values (10044, 'University of California, San Diego');
insert into Alumno (Usuario_idUsuario, Escuela) values (10048, 'Obafemi Awolowo University Ile-Ife');
insert into Alumno (Usuario_idUsuario, Escuela) values (10049, 'Mugla University');
insert into Alumno (Usuario_idUsuario, Escuela) values (10051, 'Southwestern College Santa Fe');
insert into Alumno (Usuario_idUsuario, Escuela) values (10052, 'University of Birmingham');
insert into Alumno (Usuario_idUsuario, Escuela) values (10053, 'Emeq Yizrael College');
insert into Alumno (Usuario_idUsuario, Escuela) values (10055, 'Vietnam Maritime University');
insert into Alumno (Usuario_idUsuario, Escuela) values (10056, 'Kent State University');
insert into Alumno (Usuario_idUsuario, Escuela) values (10058, 'Holy Names College');
insert into Alumno (Usuario_idUsuario, Escuela) values (10060, 'Islamic Azad University, Tehran South');
insert into Alumno (Usuario_idUsuario, Escuela) values (10063, 'Warnborough University');
insert into Alumno (Usuario_idUsuario, Escuela) values (10064, 'Universidad de Córdoba');
insert into Alumno (Usuario_idUsuario, Escuela) values (10067, 'Université Hassan II - Mohammadia');
insert into Alumno (Usuario_idUsuario, Escuela) values (10069, 'College of Science, Baghdad University');
insert into Alumno (Usuario_idUsuario, Escuela) values (10071, 'California College for Health Sciences');
insert into Alumno (Usuario_idUsuario, Escuela) values (10073, 'Guangzhou Academy of Fine Art');
insert into Alumno (Usuario_idUsuario, Escuela) values (10074, 'Ishik University');
insert into Alumno (Usuario_idUsuario, Escuela) values (10075, 'Institute of Technology and Management');
insert into Alumno (Usuario_idUsuario, Escuela) values (10077, 'Jacksonville University');
insert into Alumno (Usuario_idUsuario, Escuela) values (10078, 'Goddard College');
insert into Alumno (Usuario_idUsuario, Escuela) values (10080, 'National Institute of Mental Health and Neuro Sciences');
insert into Alumno (Usuario_idUsuario, Escuela) values (10085, 'Troy University, Phenix City');
insert into Alumno (Usuario_idUsuario, Escuela) values (10087, 'Henderson State Univerisity');
insert into Alumno (Usuario_idUsuario, Escuela) values (10088, 'Universidad Nacional de San Cristóbal de Huamanga');
insert into Alumno (Usuario_idUsuario, Escuela) values (10095, 'Claremont Graduate University');
insert into Alumno (Usuario_idUsuario, Escuela) values (10096, 'Universidad Nacional Autonoma de Nicaragua');
insert into Alumno (Usuario_idUsuario, Escuela) values (10097, 'Hokkaigakuen University of Kitami');
insert into Alumno (Usuario_idUsuario, Escuela) values (10099, 'Posts & Telecommunications Institute of Technology');
insert into Alumno (Usuario_idUsuario, Escuela) values (100102, 'Florida Institute of Technology');
insert into Alumno (Usuario_idUsuario, Escuela) values (100104, 'Philosophisch-Theologische Hochschule der Salesianer Don Boscos');
insert into Alumno (Usuario_idUsuario, Escuela) values (100106, 'Katowice School of Economics');
insert into Alumno (Usuario_idUsuario, Escuela) values (100107, 'Universidad CES');
insert into Alumno (Usuario_idUsuario, Escuela) values (100108, 'South China Construction University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100111, 'Sahmyook University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100112, 'Universidad Técnica "Federico Santa María"');
insert into Alumno (Usuario_idUsuario, Escuela) values (100113, 'Knoxville College');
insert into Alumno (Usuario_idUsuario, Escuela) values (100115, 'Hamilton Technical College');
insert into Alumno (Usuario_idUsuario, Escuela) values (100117, 'Eastern New Mexico University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100118, 'Universität Mozarteum Salzburg');
insert into Alumno (Usuario_idUsuario, Escuela) values (100119, 'Fundación Universitaria del Area Andina. Sede Pereira');
insert into Alumno (Usuario_idUsuario, Escuela) values (100121, 'Technological Education Institute of Lamia');
insert into Alumno (Usuario_idUsuario, Escuela) values (100125, 'Beijing New Asia University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100126, 'Tohoku University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100127, 'Hood College');
insert into Alumno (Usuario_idUsuario, Escuela) values (100128, 'Universidad de Extremadura');
insert into Alumno (Usuario_idUsuario, Escuela) values (100129, 'Universidade São Marcos');
insert into Alumno (Usuario_idUsuario, Escuela) values (100133, 'University of Music and Fine Arts');
insert into Alumno (Usuario_idUsuario, Escuela) values (100136, 'Instituto Universitario Nacional del Arte');
insert into Alumno (Usuario_idUsuario, Escuela) values (100137, 'University of Moncton');
insert into Alumno (Usuario_idUsuario, Escuela) values (100140, 'University of Nottingham');
insert into Alumno (Usuario_idUsuario, Escuela) values (100141, 'Knowledge College for Science and Technology');
insert into Alumno (Usuario_idUsuario, Escuela) values (100147, 'Universidade Potiguar');
insert into Alumno (Usuario_idUsuario, Escuela) values (100149, 'Karel De Grote Hogeschool');
insert into Alumno (Usuario_idUsuario, Escuela) values (100150, 'Södertörn University College');
insert into Alumno (Usuario_idUsuario, Escuela) values (100154, 'Universidad del Istmo');
insert into Alumno (Usuario_idUsuario, Escuela) values (100155, 'Fachhochschule Rosenheim, Hochschule für Technik und Wirtschaft');
insert into Alumno (Usuario_idUsuario, Escuela) values (100157, 'Kunmimg University of Science and Technology');
insert into Alumno (Usuario_idUsuario, Escuela) values (100159, 'Meiji University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100161, 'The Manchester Metropolitan University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100162, 'Universidad Nacional de Chimborazo');
insert into Alumno (Usuario_idUsuario, Escuela) values (100163, 'Ching Kuo Institue of Management & Health');
insert into Alumno (Usuario_idUsuario, Escuela) values (100165, 'Arizona State University, Downtown Phoenix Campus');
insert into Alumno (Usuario_idUsuario, Escuela) values (100166, 'Madawalabu University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100167, 'Khabarovsk State Academy of Economics and Law');
insert into Alumno (Usuario_idUsuario, Escuela) values (100169, 'Oakland University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100172, 'Guangzhou University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100173, 'Kyoritsu Pharmaceutical University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100177, 'Hebei Agricultural University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100178, 'University of Chester');
insert into Alumno (Usuario_idUsuario, Escuela) values (100184, 'Pharos International University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100185, 'Rockford College');
insert into Alumno (Usuario_idUsuario, Escuela) values (100188, 'Australian Defence Force Academy');
insert into Alumno (Usuario_idUsuario, Escuela) values (100193, 'Amravati University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100198, 'Universitas HKBP Nommensen');
insert into Alumno (Usuario_idUsuario, Escuela) values (100200, 'VanderCook College of Music');
insert into Alumno (Usuario_idUsuario, Escuela) values (100202, 'Fayetteville State University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100206, 'Whittier College');
insert into Alumno (Usuario_idUsuario, Escuela) values (100211, 'Southwest Missouri State University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100219, 'Universidad Autónoma Metropolitana - Azcapotzalco');
insert into Alumno (Usuario_idUsuario, Escuela) values (100223, 'Ohio University - Eastern');
insert into Alumno (Usuario_idUsuario, Escuela) values (100226, 'Chittagong University of Engineering and Technology');
insert into Alumno (Usuario_idUsuario, Escuela) values (100229, 'Cheljabinsk State Institute of Teacher Training');
insert into Alumno (Usuario_idUsuario, Escuela) values (100230, 'Faculdade Jaguariúna');
insert into Alumno (Usuario_idUsuario, Escuela) values (100234, 'Deutsch-Ordens Fachhochschule Riedlingen, Hochschule für Wirtschaft');
insert into Alumno (Usuario_idUsuario, Escuela) values (100237, 'Fachhochschule Kaiserslautern');
insert into Alumno (Usuario_idUsuario, Escuela) values (100238, 'Baikal National University of Economics and Law');
insert into Alumno (Usuario_idUsuario, Escuela) values (100239, 'Centro Universitário Newton Paiva');
insert into Alumno (Usuario_idUsuario, Escuela) values (100240, 'Wittenborg University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100241, 'Acadia University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100245, 'Sogang University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100246, 'Lutheran Bible Institute of Seattle');
insert into Alumno (Usuario_idUsuario, Escuela) values (100247, 'Taylor''s University College');
insert into Alumno (Usuario_idUsuario, Escuela) values (100248, 'Brunel University Uxbridge');
insert into Alumno (Usuario_idUsuario, Escuela) values (100250, 'Chongqing Medical University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100255, 'University of Toledo');
insert into Alumno (Usuario_idUsuario, Escuela) values (100256, 'Karwan Institute of Higher Education');
insert into Alumno (Usuario_idUsuario, Escuela) values (100257, 'Universitat de Vic');
insert into Alumno (Usuario_idUsuario, Escuela) values (100259, 'Chengdu University of Technology');
insert into Alumno (Usuario_idUsuario, Escuela) values (100260, 'Yazd Medical University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100264, 'University of Wolverhampton');
insert into Alumno (Usuario_idUsuario, Escuela) values (100265, 'University of Miskolc');
insert into Alumno (Usuario_idUsuario, Escuela) values (100266, 'University of Southern Europe (Monaco Business School)');
insert into Alumno (Usuario_idUsuario, Escuela) values (100267, 'Islamic Azad University, Gorgan');
insert into Alumno (Usuario_idUsuario, Escuela) values (100268, 'Technological University (Myitkyina) ');
insert into Alumno (Usuario_idUsuario, Escuela) values (100273, 'Dominican College of San Rafael');
insert into Alumno (Usuario_idUsuario, Escuela) values (100274, 'Doshisha Women''s College of Liberal Arts');
insert into Alumno (Usuario_idUsuario, Escuela) values (100275, 'Thi Qar University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100276, 'Build Bright University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100277, 'University of Phoenix');
insert into Alumno (Usuario_idUsuario, Escuela) values (100281, 'University of Da Nang');
insert into Alumno (Usuario_idUsuario, Escuela) values (100282, 'Chandra Shekhar Azad University of Agriculture and Technology');
insert into Alumno (Usuario_idUsuario, Escuela) values (100284, 'Western Governors University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100286, 'Angelo State University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100287, 'University of Presov');
insert into Alumno (Usuario_idUsuario, Escuela) values (100288, 'Universidade do Vale do Itajaí');
insert into Alumno (Usuario_idUsuario, Escuela) values (100291, 'College of the Atlantic');
insert into Alumno (Usuario_idUsuario, Escuela) values (100294, 'City University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100295, 'University of the South Pacific');
insert into Alumno (Usuario_idUsuario, Escuela) values (100296, 'Reykjavík University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100297, 'Toyo Gakuen University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100298, 'Jinan University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100305, 'University of Oxford');
insert into Alumno (Usuario_idUsuario, Escuela) values (100306, 'University of Wales, Swansea');
insert into Alumno (Usuario_idUsuario, Escuela) values (100307, 'Universidade Gregorio Semedo');
insert into Alumno (Usuario_idUsuario, Escuela) values (100308, 'United Business Institute');
insert into Alumno (Usuario_idUsuario, Escuela) values (100313, 'Instituto Tecnologico de Durango');
insert into Alumno (Usuario_idUsuario, Escuela) values (100315, 'Dominican College');
insert into Alumno (Usuario_idUsuario, Escuela) values (100317, 'Wayne State University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100319, 'Universidad de San José');
insert into Alumno (Usuario_idUsuario, Escuela) values (100320, 'Wofford College');
insert into Alumno (Usuario_idUsuario, Escuela) values (100321, 'Jissen Women''s University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100324, 'Livingstone College');
insert into Alumno (Usuario_idUsuario, Escuela) values (100327, 'Tohoku Institute of Technology');
insert into Alumno (Usuario_idUsuario, Escuela) values (100331, 'Bauder College');
insert into Alumno (Usuario_idUsuario, Escuela) values (100332, 'University of Verona');
insert into Alumno (Usuario_idUsuario, Escuela) values (100333, 'Institut Teknologi Brunei');
insert into Alumno (Usuario_idUsuario, Escuela) values (100334, 'Southern Vermont College');
insert into Alumno (Usuario_idUsuario, Escuela) values (100337, 'Universidad Gran Mariscal de Ayacucho');
insert into Alumno (Usuario_idUsuario, Escuela) values (100338, 'Isfahan University of Technology');
insert into Alumno (Usuario_idUsuario, Escuela) values (100339, 'Rajasthan Vidyapeeth University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100342, 'Shizuoka Sangyo University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100343, 'Fachhochschule Worms');
insert into Alumno (Usuario_idUsuario, Escuela) values (100345, 'Marymount College New York');
insert into Alumno (Usuario_idUsuario, Escuela) values (100346, 'Baker College of Port Huron');
insert into Alumno (Usuario_idUsuario, Escuela) values (100347, 'Indian School of Business Management and Administration');
insert into Alumno (Usuario_idUsuario, Escuela) values (100349, 'Alfred Nobel University of Economics and Law ');
insert into Alumno (Usuario_idUsuario, Escuela) values (100350, 'University of Texas at Tyler');
insert into Alumno (Usuario_idUsuario, Escuela) values (100351, 'Pan-African University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100353, 'University of Namibia');
insert into Alumno (Usuario_idUsuario, Escuela) values (100355, 'Florida Gulf Coast University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100356, 'Lindsey Wilson College');
insert into Alumno (Usuario_idUsuario, Escuela) values (100357, 'Cheju National University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100359, 'University of Sint Eustatius School of Medicine');
insert into Alumno (Usuario_idUsuario, Escuela) values (100361, 'Moldova Cooperative Trade University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100363, 'Muhlenberg College');
insert into Alumno (Usuario_idUsuario, Escuela) values (100367, 'Vilnius Academy of Arts');
insert into Alumno (Usuario_idUsuario, Escuela) values (100369, 'Universidade Federal da Paraíba');
insert into Alumno (Usuario_idUsuario, Escuela) values (100371, 'Bard College');
insert into Alumno (Usuario_idUsuario, Escuela) values (100372, 'Hilbert College');
insert into Alumno (Usuario_idUsuario, Escuela) values (100373, 'Pedagogical University of Rzeszow');
insert into Alumno (Usuario_idUsuario, Escuela) values (100374, 'Jain Vishva Bharati Institute');
insert into Alumno (Usuario_idUsuario, Escuela) values (100376, 'Universitas Sam Ratulangi');
insert into Alumno (Usuario_idUsuario, Escuela) values (100378, 'Washington State University, Vancouver');
insert into Alumno (Usuario_idUsuario, Escuela) values (100379, 'Lorestan University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100383, 'Asia Pacific Institute of Information Technology (APIIT)');
insert into Alumno (Usuario_idUsuario, Escuela) values (100385, 'Centre de Formation et de Perfectionnement des Journalistes');
insert into Alumno (Usuario_idUsuario, Escuela) values (100389, 'University College of Trollhättan/Uddevalla');
insert into Alumno (Usuario_idUsuario, Escuela) values (100391, 'Universidad Nacional de Ingenieria');
insert into Alumno (Usuario_idUsuario, Escuela) values (100392, 'Universidade da Região da Campanha');
insert into Alumno (Usuario_idUsuario, Escuela) values (100393, 'Pusan Women''s University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100395, 'Banaras Hindu University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100396, 'Hochschule für Philosophie München');
insert into Alumno (Usuario_idUsuario, Escuela) values (100401, 'Buddhist and Pali University of Sri Lanka');
insert into Alumno (Usuario_idUsuario, Escuela) values (100402, 'International Institute for Geo - Information Science and Earth Observation');
insert into Alumno (Usuario_idUsuario, Escuela) values (100409, 'North Greenville College');
insert into Alumno (Usuario_idUsuario, Escuela) values (100410, 'Kasem Bundit University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100413, 'Barat College');
insert into Alumno (Usuario_idUsuario, Escuela) values (100414, 'Université Paul Valéry (Montpellier III)');
insert into Alumno (Usuario_idUsuario, Escuela) values (100417, 'University of Luxemburg');
insert into Alumno (Usuario_idUsuario, Escuela) values (100419, 'San Jose State University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100420, 'Shanghai Lida Polytechnic Institute');
insert into Alumno (Usuario_idUsuario, Escuela) values (100423, 'IBAIS University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100424, 'Wuhan Technical University of Surveying and Mapping');
insert into Alumno (Usuario_idUsuario, Escuela) values (100425, 'Debre Markos University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100428, 'Universidad Nacional Abierta');
insert into Alumno (Usuario_idUsuario, Escuela) values (100432, 'Universidad Autónoma de Campeche');
insert into Alumno (Usuario_idUsuario, Escuela) values (100434, 'Bangladesh University of Engineering and Technology');
insert into Alumno (Usuario_idUsuario, Escuela) values (100435, 'University of Texas at Austin');
insert into Alumno (Usuario_idUsuario, Escuela) values (100436, 'Pedagogical University of Slupsk');
insert into Alumno (Usuario_idUsuario, Escuela) values (100438, 'Universidad Latinoamericana de Ciencia y Tecnologia, Panamá');
insert into Alumno (Usuario_idUsuario, Escuela) values (100439, 'Savannah State University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100440, 'Fachhochschule Bochum');
insert into Alumno (Usuario_idUsuario, Escuela) values (100444, 'East Africa University Bosaso');
insert into Alumno (Usuario_idUsuario, Escuela) values (100446, 'Universitas Muhammadiyah Magelang');
insert into Alumno (Usuario_idUsuario, Escuela) values (100448, 'Université de Tunis');
insert into Alumno (Usuario_idUsuario, Escuela) values (100450, 'Instituto Politécnico de Viana do Castelo');
insert into Alumno (Usuario_idUsuario, Escuela) values (100452, 'Ecole Supérieure Internationale d''Administration des Entreprises');
insert into Alumno (Usuario_idUsuario, Escuela) values (100456, 'Toyama Medical and Pharmaceutical University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100457, 'Aichi University of Education');
insert into Alumno (Usuario_idUsuario, Escuela) values (100458, 'Academy of the Ministry of Internal Affairs of the Republic of Belarus');
insert into Alumno (Usuario_idUsuario, Escuela) values (100459, 'Université de Béjaia');
insert into Alumno (Usuario_idUsuario, Escuela) values (100460, 'Aikoku Gakuen University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100463, 'Institut des Sciences de l''Ingénieur de Clermont-Ferrand');
insert into Alumno (Usuario_idUsuario, Escuela) values (100464, 'Maritime University in Szczecin');
insert into Alumno (Usuario_idUsuario, Escuela) values (100465, 'Kyoto Sangyo University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100466, 'Joseph Ayo Babalola University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100467, 'Sheridan College');
insert into Alumno (Usuario_idUsuario, Escuela) values (100469, 'Pedagogical University of Slupsk');
insert into Alumno (Usuario_idUsuario, Escuela) values (100471, 'Hachinohe University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100474, 'Clearwater Christian College');
insert into Alumno (Usuario_idUsuario, Escuela) values (100477, 'Primier International University Perak');
insert into Alumno (Usuario_idUsuario, Escuela) values (100478, 'Soonchunhyang University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100482, 'Liaoning University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100483, 'Atatürk University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100484, 'Fahad Bin Sultan University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100487, 'Fern-Fachhochschule Hamburg');
insert into Alumno (Usuario_idUsuario, Escuela) values (100489, 'Alagappa University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100490, 'Southwest University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100491, 'European Management School');
insert into Alumno (Usuario_idUsuario, Escuela) values (100492, 'Middle Tennessee State University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100493, 'Buddhist Acamedy of China');
insert into Alumno (Usuario_idUsuario, Escuela) values (100495, 'Institute of Textile Technology');
insert into Alumno (Usuario_idUsuario, Escuela) values (100496, 'Kunsan National University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100497, 'Razi University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100498, 'International Medical & Technological University');
insert into Alumno (Usuario_idUsuario, Escuela) values (100501, 'Donghua University, Shanghai');
