insert into Asignatura (idAsignatura, Nombre) values (1, "INTELIGENCIA ARTIFICIAL");
insert into Asignatura (idAsignatura, Nombre) values (2, "APLICACIONES MÓVILES");
insert into Asignatura (idAsignatura, Nombre) values (3, "BASE DE DATOS");
insert into Asignatura (idAsignatura, Nombre) values (4, "APLICACIONES WEB");
insert into Asignatura (idAsignatura, Nombre) values (5, "INGENIERÍA DE SOFTWARE");
insert into Asignatura (idAsignatura, Nombre) values (6, "PATTERN RECONGITION");
insert into Asignatura (idAsignatura, Nombre) values (7, "ESTRUCTURA DE DATOS");
insert into Asignatura (idAsignatura, Nombre) values (8, "CÁLCULO");
insert into Asignatura (idAsignatura, Nombre) values (9, "REDES DE COMPUTADORAS");
insert into Asignatura (idAsignatura, Nombre) values (10, "FISICA");
insert into Asignatura (idAsignatura, Nombre) values (11, "ELECTRONICA ANALOGICA");
insert into Asignatura (idAsignatura, Nombre) values (12, "PROGRAMACION ORIENTADA A OBJETOS");
insert into Asignatura (idAsignatura, Nombre) values (13, "ANALISIS Y DISEÑO ORIENTADO A OBJETOS");
insert into Asignatura (idAsignatura, Nombre) values (14, "ECUACIONES DIFERENCIALES");
insert into Asignatura (idAsignatura, Nombre) values (15, "ANALISIS DE ALGORITMOS");
insert into Asignatura (idAsignatura, Nombre) values (16, "REDES DE COMPUTADORAS");
insert into Asignatura (idAsignatura, Nombre) values (17, "MATEMATICAS DISCRETAS");
insert into Asignatura (idAsignatura, Nombre) values (18, "PROBABILIDAD Y ESTADISTICA");
insert into Asignatura (idAsignatura, Nombre) values (19, "SISTEMAS OPERATIVOS");
insert into Asignatura (idAsignatura, Nombre) values (20, "CRYPTOGRAPHY");
insert into Asignatura (idAsignatura, Nombre) values (21, "NEURAL NETWORKS");
insert into Asignatura (idAsignatura, Nombre) values (22, "WEB SECURITY");
insert into Asignatura (idAsignatura, Nombre) values (23, "GENETIC ALGORITHMS");
insert into Asignatura (idAsignatura, Nombre) values (24, "DISTRIBUTED DATA BASE");
insert into Asignatura (idAsignatura, Nombre) values (25, "DATA MINING");
